import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';

import StyledComponentsRegistry from '@/lib/styled-components-registry';
import StyleThemeProvider from '@/core/providers/StyleThemeProvider';

import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <ToastContainer />
          <StyleThemeProvider>{children}</StyleThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
